//
//  AreaRepository.m
//  SimpleCraig
//
//  Created by Adam Saladino on 12/20/13.
//  Copyright (c) 2013 StudioMDS. All rights reserved.
//

#import "AreaRepository.h"

@implementation AreaRepository

- (NSArray *) findAll {
    return @[
             [[Area alloc] initWithValue:@"318" andName:@"aberdeen"],
             [[Area alloc] initWithValue:@"364" andName:@"abilene"],
             [[Area alloc] initWithValue:@"512" andName:@"acapulco"],
             [[Area alloc] initWithValue:@"68" andName:@"adelaide"],
             [[Area alloc] initWithValue:@"450" andName:@"ahmedabad"],
             [[Area alloc] initWithValue:@"251" andName:@"akron / canton"],
             [[Area alloc] initWithValue:@"59" andName:@"albany"],
             [[Area alloc] initWithValue:@"637" andName:@"albany, GA"],
             [[Area alloc] initWithValue:@"50" andName:@"albuquerque"],
             [[Area alloc] initWithValue:@"533" andName:@"alicante"],
             [[Area alloc] initWithValue:@"355" andName:@"altoona-johnstown"],
             [[Area alloc] initWithValue:@"269" andName:@"amarillo"],
             [[Area alloc] initWithValue:@"445" andName:@"ames, IA"],
             [[Area alloc] initWithValue:@"82" andName:@"amsterdam / randstad"],
             [[Area alloc] initWithValue:@"51" andName:@"anchorage / mat-su"],
             [[Area alloc] initWithValue:@"172" andName:@"ann arbor"],
             [[Area alloc] initWithValue:@"460" andName:@"annapolis"],
             [[Area alloc] initWithValue:@"243" andName:@"appleton-oshkosh-FDL"],
             [[Area alloc] initWithValue:@"171" andName:@"asheville"],
             [[Area alloc] initWithValue:@"700" andName:@"ashtabula"],
             [[Area alloc] initWithValue:@"258" andName:@"athens, GA"],
             [[Area alloc] initWithValue:@"438" andName:@"athens, OH"],
             [[Area alloc] initWithValue:@"14" andName:@"atlanta"],
             [[Area alloc] initWithValue:@"372" andName:@"auburn"],
             [[Area alloc] initWithValue:@"69" andName:@"auckland, NZ"],
             [[Area alloc] initWithValue:@"256" andName:@"augusta"],
             [[Area alloc] initWithValue:@"15" andName:@"austin"],
             [[Area alloc] initWithValue:@"606" andName:@"bacolod"],
             [[Area alloc] initWithValue:@"406" andName:@"baja california sur"],
             [[Area alloc] initWithValue:@"63" andName:@"bakersfield"],
             [[Area alloc] initWithValue:@"534" andName:@"baleares"],
             [[Area alloc] initWithValue:@"34" andName:@"baltimore"],
             [[Area alloc] initWithValue:@"84" andName:@"bangalore"],
             [[Area alloc] initWithValue:@"295" andName:@"bangladesh"],
             [[Area alloc] initWithValue:@"83" andName:@"barcelona"],
             [[Area alloc] initWithValue:@"389" andName:@"barrie"],
             [[Area alloc] initWithValue:@"528" andName:@"basel"],
             [[Area alloc] initWithValue:@"494" andName:@"bath"],
             [[Area alloc] initWithValue:@"199" andName:@"baton rouge"],
             [[Area alloc] initWithValue:@"628" andName:@"battle creek"],
             [[Area alloc] initWithValue:@"264" andName:@"beaumont / port arthur"],
             [[Area alloc] initWithValue:@"154" andName:@"beijing"],
             [[Area alloc] initWithValue:@"296" andName:@"beirut, lebanon"],
             [[Area alloc] initWithValue:@"115" andName:@"belfast"],
             [[Area alloc] initWithValue:@"109" andName:@"belgium"],
             [[Area alloc] initWithValue:@"483" andName:@"belleville, ON"],
             [[Area alloc] initWithValue:@"217" andName:@"bellingham"],
             [[Area alloc] initWithValue:@"513" andName:@"belo horizonte"],
             [[Area alloc] initWithValue:@"663" andName:@"bemidji"],
             [[Area alloc] initWithValue:@"233" andName:@"bend"],
             [[Area alloc] initWithValue:@"108" andName:@"berlin"],
             [[Area alloc] initWithValue:@"529" andName:@"bern"],
             [[Area alloc] initWithValue:@"612" andName:@"bhubaneswar"],
             [[Area alloc] initWithValue:@"609" andName:@"bicol region"],
             [[Area alloc] initWithValue:@"535" andName:@"bilbao"],
             [[Area alloc] initWithValue:@"657" andName:@"billings"],
             [[Area alloc] initWithValue:@"248" andName:@"binghamton"],
             [[Area alloc] initWithValue:@"72" andName:@"birmingham / west mids"],
             [[Area alloc] initWithValue:@"127" andName:@"birmingham, AL"],
             [[Area alloc] initWithValue:@"666" andName:@"bismarck"],
             [[Area alloc] initWithValue:@"229" andName:@"bloomington, IN"],
             [[Area alloc] initWithValue:@"344" andName:@"bloomington-normal"],
             [[Area alloc] initWithValue:@"52" andName:@"boise"],
             [[Area alloc] initWithValue:@"578" andName:@"bolivia"],
             [[Area alloc] initWithValue:@"396" andName:@"bologna"],
             [[Area alloc] initWithValue:@"446" andName:@"boone"],
             [[Area alloc] initWithValue:@"412" andName:@"bordeaux"],
             [[Area alloc] initWithValue:@"4" andName:@"boston"],
             [[Area alloc] initWithValue:@"319" andName:@"boulder"],
             [[Area alloc] initWithValue:@"342" andName:@"bowling green"],
             [[Area alloc] initWithValue:@"658" andName:@"bozeman"],
             [[Area alloc] initWithValue:@"664" andName:@"brainerd"],
             [[Area alloc] initWithValue:@"626" andName:@"brantford-woodstock"],
             [[Area alloc] initWithValue:@"514" andName:@"brasilia"],
             [[Area alloc] initWithValue:@"522" andName:@"bremen"],
             [[Area alloc] initWithValue:@"398" andName:@"brighton"],
             [[Area alloc] initWithValue:@"66" andName:@"brisbane"],
             [[Area alloc] initWithValue:@"117" andName:@"bristol"],
             [[Area alloc] initWithValue:@"526" andName:@"brittany"],
             [[Area alloc] initWithValue:@"266" andName:@"brownsville"],
             [[Area alloc] initWithValue:@"570" andName:@"brunswick, GA"],
             [[Area alloc] initWithValue:@"153" andName:@"budapest"],
             [[Area alloc] initWithValue:@"114" andName:@"buenos aires"],
             [[Area alloc] initWithValue:@"40" andName:@"buffalo"],
             [[Area alloc] initWithValue:@"584" andName:@"bulgaria"],
             [[Area alloc] initWithValue:@"661" andName:@"butte"],
             [[Area alloc] initWithValue:@"536" andName:@"cadiz"],
             [[Area alloc] initWithValue:@"604" andName:@"cagayan de oro"],
             [[Area alloc] initWithValue:@"592" andName:@"cairns"],
             [[Area alloc] initWithValue:@"77" andName:@"calgary"],
             [[Area alloc] initWithValue:@"312" andName:@"cambridge, UK"],
             [[Area alloc] initWithValue:@"537" andName:@"canarias"],
             [[Area alloc] initWithValue:@"489" andName:@"canberra"],
             [[Area alloc] initWithValue:@"239" andName:@"cape cod / islands"],
             [[Area alloc] initWithValue:@"136" andName:@"cape town"],
             [[Area alloc] initWithValue:@"116" andName:@"cardiff / wales"],
             [[Area alloc] initWithValue:@"299" andName:@"caribbean islands"],
             [[Area alloc] initWithValue:@"621" andName:@"cariboo"],
             [[Area alloc] initWithValue:@"451" andName:@"catskills"],
             [[Area alloc] initWithValue:@"548" andName:@"cebu"],
             [[Area alloc] initWithValue:@"340" andName:@"cedar rapids"],
             [[Area alloc] initWithValue:@"644" andName:@"central louisiana"],
             [[Area alloc] initWithValue:@"434" andName:@"central michigan"],
             [[Area alloc] initWithValue:@"349" andName:@"central NJ"],
             [[Area alloc] initWithValue:@"190" andName:@"champaign urbana"],
             [[Area alloc] initWithValue:@"610" andName:@"chandigarh"],
             [[Area alloc] initWithValue:@"128" andName:@"charleston, SC"],
             [[Area alloc] initWithValue:@"439" andName:@"charleston, WV"],
             [[Area alloc] initWithValue:@"41" andName:@"charlotte"],
             [[Area alloc] initWithValue:@"290" andName:@"charlottesville"],
             [[Area alloc] initWithValue:@"484" andName:@"chatham-kent"],
             [[Area alloc] initWithValue:@"220" andName:@"chattanooga"],
             [[Area alloc] initWithValue:@"452" andName:@"chautauqua"],
             [[Area alloc] initWithValue:@"602" andName:@"chengdu"],
             [[Area alloc] initWithValue:@"182" andName:@"chennai (madras)"],
             [[Area alloc] initWithValue:@"11" andName:@"chicago"],
             [[Area alloc] initWithValue:@"187" andName:@"chico"],
             [[Area alloc] initWithValue:@"505" andName:@"chihuahua"],
             [[Area alloc] initWithValue:@"158" andName:@"chile"],
             [[Area alloc] initWithValue:@"701" andName:@"chillicothe"],
             [[Area alloc] initWithValue:@"601" andName:@"chongqing"],
             [[Area alloc] initWithValue:@"301" andName:@"christchurch"],
             [[Area alloc] initWithValue:@"35" andName:@"cincinnati, OH"],
             [[Area alloc] initWithValue:@"511" andName:@"ciudad juarez"],
             [[Area alloc] initWithValue:@"465" andName:@"clarksville, TN"],
             [[Area alloc] initWithValue:@"27" andName:@"cleveland"],
             [[Area alloc] initWithValue:@"653" andName:@"clovis / portales"],
             [[Area alloc] initWithValue:@"326" andName:@"college station"],
             [[Area alloc] initWithValue:@"313" andName:@"cologne"],
             [[Area alloc] initWithValue:@"393" andName:@"colombia"],
             [[Area alloc] initWithValue:@"210" andName:@"colorado springs"],
             [[Area alloc] initWithValue:@"222" andName:@"columbia / jeff city"],
             [[Area alloc] initWithValue:@"101" andName:@"columbia, SC"],
             [[Area alloc] initWithValue:@"42" andName:@"columbus"],
             [[Area alloc] initWithValue:@"343" andName:@"columbus, GA"],
             [[Area alloc] initWithValue:@"473" andName:@"comox valley"],
             [[Area alloc] initWithValue:@"670" andName:@"cookeville"],
             [[Area alloc] initWithValue:@"107" andName:@"copenhagen"],
             [[Area alloc] initWithValue:@"481" andName:@"cornwall, ON"],
             [[Area alloc] initWithValue:@"265" andName:@"corpus christi"],
             [[Area alloc] initWithValue:@"350" andName:@"corvallis/albany"],
             [[Area alloc] initWithValue:@"179" andName:@"costa rica"],
             [[Area alloc] initWithValue:@"495" andName:@"coventry"],
             [[Area alloc] initWithValue:@"546" andName:@"croatia"],
             [[Area alloc] initWithValue:@"705" andName:@"cumberland valley"],
             [[Area alloc] initWithValue:@"517" andName:@"curitiba"],
             [[Area alloc] initWithValue:@"600" andName:@"dalian"],
             [[Area alloc] initWithValue:@"21" andName:@"dallas / fort worth"],
             [[Area alloc] initWithValue:@"367" andName:@"danville"],
             [[Area alloc] initWithValue:@"491" andName:@"darwin"],
             [[Area alloc] initWithValue:@"547" andName:@"davao city"],
             [[Area alloc] initWithValue:@"131" andName:@"dayton / springfield"],
             [[Area alloc] initWithValue:@"238" andName:@"daytona beach"],
             [[Area alloc] initWithValue:@"569" andName:@"decatur, IL"],
             [[Area alloc] initWithValue:@"645" andName:@"deep east texas"],
             [[Area alloc] initWithValue:@"647" andName:@"del rio / eagle pass"],
             [[Area alloc] initWithValue:@"193" andName:@"delaware"],
             [[Area alloc] initWithValue:@"86" andName:@"delhi"],
             [[Area alloc] initWithValue:@"13" andName:@"denver"],
             [[Area alloc] initWithValue:@"496" andName:@"derby"],
             [[Area alloc] initWithValue:@"98" andName:@"des moines"],
             [[Area alloc] initWithValue:@"22" andName:@"detroit metro"],
             [[Area alloc] initWithValue:@"399" andName:@"devon & cornwall"],
             [[Area alloc] initWithValue:@"617" andName:@"dominican republic"],
             [[Area alloc] initWithValue:@"467" andName:@"dothan, AL"],
             [[Area alloc] initWithValue:@"521" andName:@"dresden"],
             [[Area alloc] initWithValue:@"74" andName:@"dublin"],
             [[Area alloc] initWithValue:@"362" andName:@"dubuque"],
             [[Area alloc] initWithValue:@"255" andName:@"duluth / superior"],
             [[Area alloc] initWithValue:@"498" andName:@"dundee"],
             [[Area alloc] initWithValue:@"594" andName:@"dunedin"],
             [[Area alloc] initWithValue:@"303" andName:@"durban"],
             [[Area alloc] initWithValue:@"418" andName:@"dusseldorf"],
             [[Area alloc] initWithValue:@"402" andName:@"east anglia"],
             [[Area alloc] initWithValue:@"424" andName:@"east idaho"],
             [[Area alloc] initWithValue:@"400" andName:@"east midlands"],
             [[Area alloc] initWithValue:@"322" andName:@"east oregon"],
             [[Area alloc] initWithValue:@"713" andName:@"eastern CO"],
             [[Area alloc] initWithValue:@"281" andName:@"eastern CT"],
             [[Area alloc] initWithValue:@"674" andName:@"eastern kentucky"],
             [[Area alloc] initWithValue:@"192" andName:@"eastern montana"],
             [[Area alloc] initWithValue:@"335" andName:@"eastern NC"],
             [[Area alloc] initWithValue:@"444" andName:@"eastern panhandle"],
             [[Area alloc] initWithValue:@"328" andName:@"eastern shore"],
             [[Area alloc] initWithValue:@"242" andName:@"eau claire"],
             [[Area alloc] initWithValue:@"545" andName:@"ecuador"],
             [[Area alloc] initWithValue:@"75" andName:@"edinburgh"],
             [[Area alloc] initWithValue:@"78" andName:@"edmonton"],
             [[Area alloc] initWithValue:@"162" andName:@"egypt"],
             [[Area alloc] initWithValue:@"132" andName:@"el paso"],
             [[Area alloc] initWithValue:@"587" andName:@"el salvador"],
             [[Area alloc] initWithValue:@"652" andName:@"elko"],
             [[Area alloc] initWithValue:@"453" andName:@"elmira-corning"],
             [[Area alloc] initWithValue:@"275" andName:@"erie, PA"],
             [[Area alloc] initWithValue:@"523" andName:@"essen / ruhr"],
             [[Area alloc] initWithValue:@"497" andName:@"essex"],
             [[Area alloc] initWithValue:@"576" andName:@"ethiopia"],
             [[Area alloc] initWithValue:@"94" andName:@"eugene"],
             [[Area alloc] initWithValue:@"227" andName:@"evansville"],
             [[Area alloc] initWithValue:@"677" andName:@"fairbanks"],
             [[Area alloc] initWithValue:@"435" andName:@"fargo / moorhead"],
             [[Area alloc] initWithValue:@"568" andName:@"farmington, NM"],
             [[Area alloc] initWithValue:@"542" andName:@"faro / algarve"],
             [[Area alloc] initWithValue:@"273" andName:@"fayetteville"],
             [[Area alloc] initWithValue:@"293" andName:@"fayetteville, AR"],
             [[Area alloc] initWithValue:@"685" andName:@"finger lakes"],
             [[Area alloc] initWithValue:@"145" andName:@"finland"],
             [[Area alloc] initWithValue:@"244" andName:@"flagstaff / sedona"],
             [[Area alloc] initWithValue:@"259" andName:@"flint"],
             [[Area alloc] initWithValue:@"560" andName:@"florence / muscle shoals"],
             [[Area alloc] initWithValue:@"152" andName:@"florence / tuscany"],
             [[Area alloc] initWithValue:@"464" andName:@"florence, SC"],
             [[Area alloc] initWithValue:@"330" andName:@"florida keys"],
             [[Area alloc] initWithValue:@"287" andName:@"fort collins / north CO"],
             [[Area alloc] initWithValue:@"693" andName:@"fort dodge"],
             [[Area alloc] initWithValue:@"358" andName:@"fort smith, AR"],
             [[Area alloc] initWithValue:@"226" andName:@"fort wayne"],
             [[Area alloc] initWithValue:@"518" andName:@"fortaleza"],
             [[Area alloc] initWithValue:@"141" andName:@"frankfurt"],
             [[Area alloc] initWithValue:@"471" andName:@"fraser valley"],
             [[Area alloc] initWithValue:@"633" andName:@"frederick"],
             [[Area alloc] initWithValue:@"457" andName:@"fredericksburg"],
             [[Area alloc] initWithValue:@"43" andName:@"fresno / madera"],
             [[Area alloc] initWithValue:@"477" andName:@"ft mcmurray"],
             [[Area alloc] initWithValue:@"125" andName:@"ft myers / SW florida"],
             [[Area alloc] initWithValue:@"503" andName:@"fukuoka"],
             [[Area alloc] initWithValue:@"559" andName:@"gadsden-anniston"],
             [[Area alloc] initWithValue:@"219" andName:@"gainesville"],
             [[Area alloc] initWithValue:@"470" andName:@"galveston"],
             [[Area alloc] initWithValue:@"146" andName:@"geneva"],
             [[Area alloc] initWithValue:@"531" andName:@"genoa"],
             [[Area alloc] initWithValue:@"575" andName:@"ghana"],
             [[Area alloc] initWithValue:@"73" andName:@"glasgow"],
             [[Area alloc] initWithValue:@"686" andName:@"glens falls"],
             [[Area alloc] initWithValue:@"430" andName:@"goa"],
             [[Area alloc] initWithValue:@"590" andName:@"gold coast"],
             [[Area alloc] initWithValue:@"373" andName:@"gold country"],
             [[Area alloc] initWithValue:@"538" andName:@"granada"],
             [[Area alloc] initWithValue:@"667" andName:@"grand forks"],
             [[Area alloc] initWithValue:@"432" andName:@"grand island"],
             [[Area alloc] initWithValue:@"129" andName:@"grand rapids"],
             [[Area alloc] initWithValue:@"660" andName:@"great falls"],
             [[Area alloc] initWithValue:@"144" andName:@"greece"],
             [[Area alloc] initWithValue:@"241" andName:@"green bay"],
             [[Area alloc] initWithValue:@"61" andName:@"greensboro"],
             [[Area alloc] initWithValue:@"253" andName:@"greenville / upstate"],
             [[Area alloc] initWithValue:@"525" andName:@"grenoble"],
             [[Area alloc] initWithValue:@"404" andName:@"guadalajara"],
             [[Area alloc] initWithValue:@"245" andName:@"guam-micronesia"],
             [[Area alloc] initWithValue:@"431" andName:@"guanajuato"],
             [[Area alloc] initWithValue:@"409" andName:@"guangzhou"],
             [[Area alloc] initWithValue:@"585" andName:@"guatemala"],
             [[Area alloc] initWithValue:@"482" andName:@"guelph"],
             [[Area alloc] initWithValue:@"230" andName:@"gulfport / biloxi"],
             [[Area alloc] initWithValue:@"391" andName:@"haifa"],
             [[Area alloc] initWithValue:@"174" andName:@"halifax"],
             [[Area alloc] initWithValue:@"140" andName:@"hamburg"],
             [[Area alloc] initWithValue:@"213" andName:@"hamilton-burlington"],
             [[Area alloc] initWithValue:@"403" andName:@"hampshire"],
             [[Area alloc] initWithValue:@"48" andName:@"hampton roads"],
             [[Area alloc] initWithValue:@"709" andName:@"hanford-corcoran"],
             [[Area alloc] initWithValue:@"500" andName:@"hangzhou"],
             [[Area alloc] initWithValue:@"417" andName:@"hannover"],
             [[Area alloc] initWithValue:@"166" andName:@"harrisburg"],
             [[Area alloc] initWithValue:@"447" andName:@"harrisonburg"],
             [[Area alloc] initWithValue:@"44" andName:@"hartford"],
             [[Area alloc] initWithValue:@"374" andName:@"hattiesburg"],
             [[Area alloc] initWithValue:@"28" andName:@"hawaii"],
             [[Area alloc] initWithValue:@"639" andName:@"heartland florida"],
             [[Area alloc] initWithValue:@"519" andName:@"heidelberg"],
             [[Area alloc] initWithValue:@"659" andName:@"helena"],
             [[Area alloc] initWithValue:@"506" andName:@"hermosillo"],
             [[Area alloc] initWithValue:@"462" andName:@"hickory / lenoir"],
             [[Area alloc] initWithValue:@"288" andName:@"high rockies"],
             [[Area alloc] initWithValue:@"353" andName:@"hilton head"],
             [[Area alloc] initWithValue:@"504" andName:@"hiroshima"],
             [[Area alloc] initWithValue:@"630" andName:@"holland"],
             [[Area alloc] initWithValue:@"87" andName:@"hong kong"],
             [[Area alloc] initWithValue:@"643" andName:@"houma"],
             [[Area alloc] initWithValue:@"23" andName:@"houston"],
             [[Area alloc] initWithValue:@"249" andName:@"hudson valley"],
             [[Area alloc] initWithValue:@"189" andName:@"humboldt county"],
             [[Area alloc] initWithValue:@"442" andName:@"huntington-ashland"],
             [[Area alloc] initWithValue:@"231" andName:@"huntsville / decatur"],
             [[Area alloc] initWithValue:@"183" andName:@"hyderabad"],
             [[Area alloc] initWithValue:@"605" andName:@"iloilo"],
             [[Area alloc] initWithValue:@"455" andName:@"imperial county"],
             [[Area alloc] initWithValue:@"45" andName:@"indianapolis"],
             [[Area alloc] initWithValue:@"157" andName:@"indonesia"],
             [[Area alloc] initWithValue:@"549" andName:@"indore"],
             [[Area alloc] initWithValue:@"104" andName:@"inland empire"],
             [[Area alloc] initWithValue:@"339" andName:@"iowa city"],
             [[Area alloc] initWithValue:@"589" andName:@"iran"],
             [[Area alloc] initWithValue:@"588" andName:@"iraq"],
             [[Area alloc] initWithValue:@"201" andName:@"ithaca"],
             [[Area alloc] initWithValue:@"426" andName:@"jackson, MI"],
             [[Area alloc] initWithValue:@"134" andName:@"jackson, MS"],
             [[Area alloc] initWithValue:@"558" andName:@"jackson, TN"],
             [[Area alloc] initWithValue:@"80" andName:@"jacksonville"],
             [[Area alloc] initWithValue:@"634" andName:@"jacksonville, NC"],
             [[Area alloc] initWithValue:@"550" andName:@"jaipur"],
             [[Area alloc] initWithValue:@"553" andName:@"janesville"],
             [[Area alloc] initWithValue:@"561" andName:@"jersey shore"],
             [[Area alloc] initWithValue:@"161" andName:@"jerusalem"],
             [[Area alloc] initWithValue:@"185" andName:@"johannesburg"],
             [[Area alloc] initWithValue:@"425" andName:@"jonesboro"],
             [[Area alloc] initWithValue:@"423" andName:@"joplin"],
             [[Area alloc] initWithValue:@"618" andName:@"kaiserslautern"],
             [[Area alloc] initWithValue:@"261" andName:@"kalamazoo"],
             [[Area alloc] initWithValue:@"662" andName:@"kalispell"],
             [[Area alloc] initWithValue:@"381" andName:@"kamloops"],
             [[Area alloc] initWithValue:@"30" andName:@"kansas city, MO"],
             [[Area alloc] initWithValue:@"380" andName:@"kelowna / okanagan"],
             [[Area alloc] initWithValue:@"678" andName:@"kenai peninsula"],
             [[Area alloc] initWithValue:@"324" andName:@"kennewick-pasco-richland"],
             [[Area alloc] initWithValue:@"552" andName:@"kenosha-racine"],
             [[Area alloc] initWithValue:@"493" andName:@"kent"],
             [[Area alloc] initWithValue:@"582" andName:@"kenya"],
             [[Area alloc] initWithValue:@"410" andName:@"kerala"],
             [[Area alloc] initWithValue:@"327" andName:@"killeen / temple / ft hood"],
             [[Area alloc] initWithValue:@"385" andName:@"kingston, ON"],
             [[Area alloc] initWithValue:@"696" andName:@"kirksville"],
             [[Area alloc] initWithValue:@"214" andName:@"kitchener-waterloo-cambridge"],
             [[Area alloc] initWithValue:@"675" andName:@"klamath falls"],
             [[Area alloc] initWithValue:@"202" andName:@"knoxville"],
             [[Area alloc] initWithValue:@"672" andName:@"kokomo"],
             [[Area alloc] initWithValue:@"184" andName:@"kolkata (calcutta)"],
             [[Area alloc] initWithValue:@"474" andName:@"kootenays"],
             [[Area alloc] initWithValue:@"577" andName:@"kuwait"],
             [[Area alloc] initWithValue:@"363" andName:@"la crosse"],
             [[Area alloc] initWithValue:@"698" andName:@"la salle co"],
             [[Area alloc] initWithValue:@"283" andName:@"lafayette"],
             [[Area alloc] initWithValue:@"360" andName:@"lafayette / west lafayette"],
             [[Area alloc] initWithValue:@"284" andName:@"lake charles"],
             [[Area alloc] initWithValue:@"695" andName:@"lake of the ozarks"],
             [[Area alloc] initWithValue:@"376" andName:@"lakeland"],
             [[Area alloc] initWithValue:@"279" andName:@"lancaster, PA"],
             [[Area alloc] initWithValue:@"212" andName:@"lansing"],
             [[Area alloc] initWithValue:@"271" andName:@"laredo"],
             [[Area alloc] initWithValue:@"334" andName:@"las cruces"],
             [[Area alloc] initWithValue:@"26" andName:@"las vegas"],
             [[Area alloc] initWithValue:@"615" andName:@"lausanne"],
             [[Area alloc] initWithValue:@"347" andName:@"lawrence"],
             [[Area alloc] initWithValue:@"422" andName:@"lawton"],
             [[Area alloc] initWithValue:@"123" andName:@"leeds"],
             [[Area alloc] initWithValue:@"167" andName:@"lehigh valley"],
             [[Area alloc] initWithValue:@"520" andName:@"leipzig"],
             [[Area alloc] initWithValue:@"476" andName:@"lethbridge"],
             [[Area alloc] initWithValue:@"654" andName:@"lewiston / clarkston"],
             [[Area alloc] initWithValue:@"133" andName:@"lexington, KY"],
             [[Area alloc] initWithValue:@"413" andName:@"lille"],
             [[Area alloc] initWithValue:@"437" andName:@"lima / findlay"],
             [[Area alloc] initWithValue:@"282" andName:@"lincoln"],
             [[Area alloc] initWithValue:@"540" andName:@"lisbon"],
             [[Area alloc] initWithValue:@"100" andName:@"little rock"],
             [[Area alloc] initWithValue:@"118" andName:@"liverpool"],
             [[Area alloc] initWithValue:@"448" andName:@"logan"],
             [[Area alloc] initWithValue:@"415" andName:@"loire valley"],
             [[Area alloc] initWithValue:@"24" andName:@"london"],
             [[Area alloc] initWithValue:@"234" andName:@"london, ON"],
             [[Area alloc] initWithValue:@"250" andName:@"long island"],
             [[Area alloc] initWithValue:@"7" andName:@"los angeles"],
             [[Area alloc] initWithValue:@"58" andName:@"louisville"],
             [[Area alloc] initWithValue:@"267" andName:@"lubbock"],
             [[Area alloc] initWithValue:@"611" andName:@"lucknow"],
             [[Area alloc] initWithValue:@"544" andName:@"luxembourg"],
             [[Area alloc] initWithValue:@"366" andName:@"lynchburg"],
             [[Area alloc] initWithValue:@"150" andName:@"lyon"],
             [[Area alloc] initWithValue:@"257" andName:@"macon / warner robins"],
             [[Area alloc] initWithValue:@"165" andName:@"madison"],
             [[Area alloc] initWithValue:@"110" andName:@"madrid"],
             [[Area alloc] initWithValue:@"169" andName:@"maine"],
             [[Area alloc] initWithValue:@"539" andName:@"malaga"],
             [[Area alloc] initWithValue:@"297" andName:@"malaysia"],
             [[Area alloc] initWithValue:@"71" andName:@"manchester"],
             [[Area alloc] initWithValue:@"428" andName:@"manhattan, KS"],
             [[Area alloc] initWithValue:@"90" andName:@"manila"],
             [[Area alloc] initWithValue:@"421" andName:@"mankato"],
             [[Area alloc] initWithValue:@"436" andName:@"mansfield"],
             [[Area alloc] initWithValue:@"149" andName:@"marseille"],
             [[Area alloc] initWithValue:@"692" andName:@"mason city"],
             [[Area alloc] initWithValue:@"699" andName:@"mattoon-charleston"],
             [[Area alloc] initWithValue:@"509" andName:@"mazatlan"],
             [[Area alloc] initWithValue:@"263" andName:@"mcallen / edinburg"],
             [[Area alloc] initWithValue:@"706" andName:@"meadville"],
             [[Area alloc] initWithValue:@"216" andName:@"medford-ashland"],
             [[Area alloc] initWithValue:@"619" andName:@"medicine hat"],
             [[Area alloc] initWithValue:@"65" andName:@"melbourne"],
             [[Area alloc] initWithValue:@"46" andName:@"memphis, TN"],
             [[Area alloc] initWithValue:@"454" andName:@"mendocino county"],
             [[Area alloc] initWithValue:@"285" andName:@"merced"],
             [[Area alloc] initWithValue:@"641" andName:@"meridian"],
             [[Area alloc] initWithValue:@"91" andName:@"mexico city"],
             [[Area alloc] initWithValue:@"111" andName:@"milan"],
             [[Area alloc] initWithValue:@"47" andName:@"milwaukee"],
             [[Area alloc] initWithValue:@"19" andName:@"minneapolis / st paul"],
             [[Area alloc] initWithValue:@"656" andName:@"missoula"],
             [[Area alloc] initWithValue:@"200" andName:@"mobile"],
             [[Area alloc] initWithValue:@"96" andName:@"modesto"],
             [[Area alloc] initWithValue:@"565" andName:@"mohave county"],
             [[Area alloc] initWithValue:@"629" andName:@"monroe"],
             [[Area alloc] initWithValue:@"563" andName:@"monroe, LA"],
             [[Area alloc] initWithValue:@"102" andName:@"monterey bay"],
             [[Area alloc] initWithValue:@"408" andName:@"monterrey"],
             [[Area alloc] initWithValue:@"543" andName:@"montevideo"],
             [[Area alloc] initWithValue:@"207" andName:@"montgomery"],
             [[Area alloc] initWithValue:@"524" andName:@"montpellier"],
             [[Area alloc] initWithValue:@"49" andName:@"montreal"],
             [[Area alloc] initWithValue:@"440" andName:@"morgantown"],
             [[Area alloc] initWithValue:@"580" andName:@"morocco"],
             [[Area alloc] initWithValue:@"137" andName:@"moscow"],
             [[Area alloc] initWithValue:@"655" andName:@"moses lake"],
             [[Area alloc] initWithValue:@"85" andName:@"mumbai"],
             [[Area alloc] initWithValue:@"361" andName:@"muncie / anderson"],
             [[Area alloc] initWithValue:@"142" andName:@"munich"],
             [[Area alloc] initWithValue:@"554" andName:@"muskegon"],
             [[Area alloc] initWithValue:@"254" andName:@"myrtle beach"],
             [[Area alloc] initWithValue:@"501" andName:@"nagoya"],
             [[Area alloc] initWithValue:@"382" andName:@"nanaimo"],
             [[Area alloc] initWithValue:@"599" andName:@"nanjing"],
             [[Area alloc] initWithValue:@"151" andName:@"napoli / campania"],
             [[Area alloc] initWithValue:@"32" andName:@"nashville"],
             [[Area alloc] initWithValue:@"379" andName:@"new brunswick"],
             [[Area alloc] initWithValue:@"198" andName:@"new hampshire"],
             [[Area alloc] initWithValue:@"168" andName:@"new haven"],
             [[Area alloc] initWithValue:@"31" andName:@"new orleans"],
             [[Area alloc] initWithValue:@"291" andName:@"new river valley"],
             [[Area alloc] initWithValue:@"3" andName:@"new york city"],
             [[Area alloc] initWithValue:@"163" andName:@"newcastle / NE england"],
             [[Area alloc] initWithValue:@"591" andName:@"newcastle, NSW"],
             [[Area alloc] initWithValue:@"386" andName:@"niagara region"],
             [[Area alloc] initWithValue:@"586" andName:@"nicaragua"],
             [[Area alloc] initWithValue:@"306" andName:@"nice / cote d'azur"],
             [[Area alloc] initWithValue:@"527" andName:@"normandy"],
             [[Area alloc] initWithValue:@"638" andName:@"north central FL"],
             [[Area alloc] initWithValue:@"196" andName:@"north dakota"],
             [[Area alloc] initWithValue:@"170" andName:@"north jersey"],
             [[Area alloc] initWithValue:@"375" andName:@"north mississippi"],
             [[Area alloc] initWithValue:@"668" andName:@"north platte"],
             [[Area alloc] initWithValue:@"682" andName:@"northeast SD"],
             [[Area alloc] initWithValue:@"309" andName:@"northern michigan"],
             [[Area alloc] initWithValue:@"443" andName:@"northern panhandle"],
             [[Area alloc] initWithValue:@"631" andName:@"northern WI"],
             [[Area alloc] initWithValue:@"354" andName:@"northwest CT"],
             [[Area alloc] initWithValue:@"636" andName:@"northwest GA"],
             [[Area alloc] initWithValue:@"688" andName:@"northwest KS"],
             [[Area alloc] initWithValue:@"650" andName:@"northwest OK"],
             [[Area alloc] initWithValue:@"105" andName:@"norway"],
             [[Area alloc] initWithValue:@"492" andName:@"nottingham"],
             [[Area alloc] initWithValue:@"614" andName:@"nuremberg"],
             [[Area alloc] initWithValue:@"510" andName:@"oaxaca"],
             [[Area alloc] initWithValue:@"333" andName:@"ocala"],
             [[Area alloc] initWithValue:@"268" andName:@"odessa / midland"],
             [[Area alloc] initWithValue:@"351" andName:@"ogden-clearfield"],
             [[Area alloc] initWithValue:@"640" andName:@"okaloosa / walton"],
             [[Area alloc] initWithValue:@"429" andName:@"okinawa"],
             [[Area alloc] initWithValue:@"54" andName:@"oklahoma city"],
             [[Area alloc] initWithValue:@"466" andName:@"olympic peninsula"],
             [[Area alloc] initWithValue:@"55" andName:@"omaha / council bluffs"],
             [[Area alloc] initWithValue:@"684" andName:@"oneonta"],
             [[Area alloc] initWithValue:@"103" andName:@"orange county"],
             [[Area alloc] initWithValue:@"321" andName:@"oregon coast"],
             [[Area alloc] initWithValue:@"39" andName:@"orlando"],
             [[Area alloc] initWithValue:@"120" andName:@"osaka-kobe-kyoto"],
             [[Area alloc] initWithValue:@"76" andName:@"ottawa-hull-gatineau"],
             [[Area alloc] initWithValue:@"336" andName:@"outer banks"],
             [[Area alloc] initWithValue:@"487" andName:@"owen sound"],
             [[Area alloc] initWithValue:@"673" andName:@"owensboro"],
             [[Area alloc] initWithValue:@"211" andName:@"oxford"],
             [[Area alloc] initWithValue:@"294" andName:@"pakistan"],
             [[Area alloc] initWithValue:@"209" andName:@"palm springs, CA"],
             [[Area alloc] initWithValue:@"608" andName:@"pampanga"],
             [[Area alloc] initWithValue:@"298" andName:@"panama"],
             [[Area alloc] initWithValue:@"562" andName:@"panama city, FL"],
             [[Area alloc] initWithValue:@"81" andName:@"paris"],
             [[Area alloc] initWithValue:@"441" andName:@"parkersburg-marietta"],
             [[Area alloc] initWithValue:@"620" andName:@"peace river country"],
             [[Area alloc] initWithValue:@"203" andName:@"pensacola"],
             [[Area alloc] initWithValue:@"224" andName:@"peoria"],
             [[Area alloc] initWithValue:@"67" andName:@"perth"],
             [[Area alloc] initWithValue:@"159" andName:@"peru"],
             [[Area alloc] initWithValue:@"530" andName:@"perugia"],
             [[Area alloc] initWithValue:@"388" andName:@"peterborough"],
             [[Area alloc] initWithValue:@"17" andName:@"philadelphia"],
             [[Area alloc] initWithValue:@"18" andName:@"phoenix"],
             [[Area alloc] initWithValue:@"681" andName:@"pierre / central SD"],
             [[Area alloc] initWithValue:@"33" andName:@"pittsburgh"],
             [[Area alloc] initWithValue:@"338" andName:@"plattsburgh-adirondacks"],
             [[Area alloc] initWithValue:@"356" andName:@"poconos"],
             [[Area alloc] initWithValue:@"147" andName:@"poland"],
             [[Area alloc] initWithValue:@"555" andName:@"port huron"],
             [[Area alloc] initWithValue:@"9" andName:@"portland, OR"],
             [[Area alloc] initWithValue:@"541" andName:@"porto"],
             [[Area alloc] initWithValue:@"515" andName:@"porto alegre"],
             [[Area alloc] initWithValue:@"683" andName:@"potsdam-canton-massena"],
             [[Area alloc] initWithValue:@"138" andName:@"prague"],
             [[Area alloc] initWithValue:@"419" andName:@"prescott"],
             [[Area alloc] initWithValue:@"595" andName:@"pretoria"],
             [[Area alloc] initWithValue:@"304" andName:@"prince edward island"],
             [[Area alloc] initWithValue:@"383" andName:@"prince george"],
             [[Area alloc] initWithValue:@"292" andName:@"provo / orem"],
             [[Area alloc] initWithValue:@"508" andName:@"puebla"],
             [[Area alloc] initWithValue:@"315" andName:@"pueblo"],
             [[Area alloc] initWithValue:@"180" andName:@"puerto rico"],
             [[Area alloc] initWithValue:@"407" andName:@"puerto vallarta"],
             [[Area alloc] initWithValue:@"368" andName:@"pullman / moscow"],
             [[Area alloc] initWithValue:@"317" andName:@"pune"],
             [[Area alloc] initWithValue:@"307" andName:@"quad cities, IA/IL"],
             [[Area alloc] initWithValue:@"175" andName:@"quebec city"],
             [[Area alloc] initWithValue:@"36" andName:@"raleigh / durham / CH"],
             [[Area alloc] initWithValue:@"680" andName:@"rapid city / west SD"],
             [[Area alloc] initWithValue:@"278" andName:@"reading"],
             [[Area alloc] initWithValue:@"516" andName:@"recife"],
             [[Area alloc] initWithValue:@"475" andName:@"red deer"],
             [[Area alloc] initWithValue:@"188" andName:@"redding"],
             [[Area alloc] initWithValue:@"478" andName:@"regina"],
             [[Area alloc] initWithValue:@"92" andName:@"reno / tahoe"],
             [[Area alloc] initWithValue:@"579" andName:@"reykjavik"],
             [[Area alloc] initWithValue:@"38" andName:@"rhode island"],
             [[Area alloc] initWithValue:@"60" andName:@"richmond"],
             [[Area alloc] initWithValue:@"671" andName:@"richmond, IN"],
             [[Area alloc] initWithValue:@"139" andName:@"rio de janeiro"],
             [[Area alloc] initWithValue:@"289" andName:@"roanoke"],
             [[Area alloc] initWithValue:@"316" andName:@"rochester, MN"],
             [[Area alloc] initWithValue:@"126" andName:@"rochester, NY"],
             [[Area alloc] initWithValue:@"223" andName:@"rockford"],
             [[Area alloc] initWithValue:@"574" andName:@"romania"],
             [[Area alloc] initWithValue:@"121" andName:@"rome"],
             [[Area alloc] initWithValue:@"459" andName:@"roseburg"],
             [[Area alloc] initWithValue:@"420" andName:@"roswell / carlsbad"],
             [[Area alloc] initWithValue:@"12" andName:@"sacramento"],
             [[Area alloc] initWithValue:@"260" andName:@"saginaw-midland-baycity"],
             [[Area alloc] initWithValue:@"480" andName:@"saguenay"],
             [[Area alloc] initWithValue:@"232" andName:@"salem, OR"],
             [[Area alloc] initWithValue:@"690" andName:@"salina"],
             [[Area alloc] initWithValue:@"56" andName:@"salt lake city"],
             [[Area alloc] initWithValue:@"392" andName:@"salvador, bahia"],
             [[Area alloc] initWithValue:@"646" andName:@"san angelo"],
             [[Area alloc] initWithValue:@"53" andName:@"san antonio"],
             [[Area alloc] initWithValue:@"8" andName:@"san diego"],
             [[Area alloc] initWithValue:@"191" andName:@"san luis obispo"],
             [[Area alloc] initWithValue:@"449" andName:@"san marcos"],
             [[Area alloc] initWithValue:@"573" andName:@"sandusky"],
             [[Area alloc] initWithValue:@"62" andName:@"santa barbara"],
             [[Area alloc] initWithValue:@"218" andName:@"santa fe / taos"],
             [[Area alloc] initWithValue:@"710" andName:@"santa maria"],
             [[Area alloc] initWithValue:@"113" andName:@"sao paulo"],
             [[Area alloc] initWithValue:@"502" andName:@"sapporo"],
             [[Area alloc] initWithValue:@"237" andName:@"sarasota-bradenton"],
             [[Area alloc] initWithValue:@"532" andName:@"sardinia"],
             [[Area alloc] initWithValue:@"486" andName:@"sarnia"],
             [[Area alloc] initWithValue:@"176" andName:@"saskatoon"],
             [[Area alloc] initWithValue:@"485" andName:@"sault ste marie, ON"],
             [[Area alloc] initWithValue:@"205" andName:@"savannah / hinesville"],
             [[Area alloc] initWithValue:@"669" andName:@"scottsbluff / panhandle"],
             [[Area alloc] initWithValue:@"276" andName:@"scranton / wilkes-barre"],
             [[Area alloc] initWithValue:@"2" andName:@"seattle-tacoma"],
             [[Area alloc] initWithValue:@"596" andName:@"sendai"],
             [[Area alloc] initWithValue:@"119" andName:@"seoul"],
             [[Area alloc] initWithValue:@"395" andName:@"sevilla"],
             [[Area alloc] initWithValue:@"1" andName:@"SF bay area"],
             [[Area alloc] initWithValue:@"135" andName:@"shanghai"],
             [[Area alloc] initWithValue:@"571" andName:@"sheboygan, WI"],
             [[Area alloc] initWithValue:@"401" andName:@"sheffield"],
             [[Area alloc] initWithValue:@"598" andName:@"shenyang"],
             [[Area alloc] initWithValue:@"499" andName:@"shenzhen"],
             [[Area alloc] initWithValue:@"390" andName:@"sherbrooke"],
             [[Area alloc] initWithValue:@"651" andName:@"show low"],
             [[Area alloc] initWithValue:@"206" andName:@"shreveport"],
             [[Area alloc] initWithValue:@"311" andName:@"sicilia"],
             [[Area alloc] initWithValue:@"468" andName:@"sierra vista"],
             [[Area alloc] initWithValue:@"89" andName:@"singapore"],
             [[Area alloc] initWithValue:@"341" andName:@"sioux city, IA"],
             [[Area alloc] initWithValue:@"679" andName:@"sioux falls / SE SD"],
             [[Area alloc] initWithValue:@"708" andName:@"siskiyou county"],
             [[Area alloc] initWithValue:@"461" andName:@"skagit / island / SJI"],
             [[Area alloc] initWithValue:@"623" andName:@"skeena-bulkley"],
             [[Area alloc] initWithValue:@"228" andName:@"south bend / michiana"],
             [[Area alloc] initWithValue:@"378" andName:@"south coast"],
             [[Area alloc] initWithValue:@"195" andName:@"south dakota"],
             [[Area alloc] initWithValue:@"20" andName:@"south florida"],
             [[Area alloc] initWithValue:@"286" andName:@"south jersey"],
             [[Area alloc] initWithValue:@"676" andName:@"southeast alaska"],
             [[Area alloc] initWithValue:@"691" andName:@"southeast IA"],
             [[Area alloc] initWithValue:@"689" andName:@"southeast KS"],
             [[Area alloc] initWithValue:@"566" andName:@"southeast missouri"],
             [[Area alloc] initWithValue:@"345" andName:@"southern illinois"],
             [[Area alloc] initWithValue:@"556" andName:@"southern maryland"],
             [[Area alloc] initWithValue:@"632" andName:@"southern WV"],
             [[Area alloc] initWithValue:@"687" andName:@"southwest KS"],
             [[Area alloc] initWithValue:@"572" andName:@"southwest michigan"],
             [[Area alloc] initWithValue:@"665" andName:@"southwest MN"],
             [[Area alloc] initWithValue:@"642" andName:@"southwest MS"],
             [[Area alloc] initWithValue:@"648" andName:@"southwest TX"],
             [[Area alloc] initWithValue:@"712" andName:@"southwest VA"],
             [[Area alloc] initWithValue:@"331" andName:@"space coast"],
             [[Area alloc] initWithValue:@"95" andName:@"spokane / coeur d'alene"],
             [[Area alloc] initWithValue:@"225" andName:@"springfield, IL"],
             [[Area alloc] initWithValue:@"221" andName:@"springfield, MO"],
             [[Area alloc] initWithValue:@"557" andName:@"st augustine"],
             [[Area alloc] initWithValue:@"369" andName:@"st cloud"],
             [[Area alloc] initWithValue:@"352" andName:@"st george"],
             [[Area alloc] initWithValue:@"305" andName:@"st john's, NL"],
             [[Area alloc] initWithValue:@"694" andName:@"st joseph"],
             [[Area alloc] initWithValue:@"29" andName:@"st louis, MO"],
             [[Area alloc] initWithValue:@"143" andName:@"st petersburg, RU"],
             [[Area alloc] initWithValue:@"277" andName:@"state college"],
             [[Area alloc] initWithValue:@"635" andName:@"statesboro"],
             [[Area alloc] initWithValue:@"433" andName:@"stillwater"],
             [[Area alloc] initWithValue:@"97" andName:@"stockton"],
             [[Area alloc] initWithValue:@"414" andName:@"strasbourg"],
             [[Area alloc] initWithValue:@"416" andName:@"stuttgart"],
             [[Area alloc] initWithValue:@"384" andName:@"sudbury"],
             [[Area alloc] initWithValue:@"622" andName:@"sunshine coast"],
             [[Area alloc] initWithValue:@"613" andName:@"surat surat"],
             [[Area alloc] initWithValue:@"707" andName:@"susanville"],
             [[Area alloc] initWithValue:@"106" andName:@"sweden"],
             [[Area alloc] initWithValue:@"64" andName:@"sydney"],
             [[Area alloc] initWithValue:@"130" andName:@"syracuse"],
             [[Area alloc] initWithValue:@"155" andName:@"taiwan"],
             [[Area alloc] initWithValue:@"186" andName:@"tallahassee"],
             [[Area alloc] initWithValue:@"37" andName:@"tampa bay area"],
             [[Area alloc] initWithValue:@"490" andName:@"tasmania"],
             [[Area alloc] initWithValue:@"160" andName:@"tel aviv"],
             [[Area alloc] initWithValue:@"348" andName:@"terre haute"],
             [[Area alloc] initWithValue:@"488" andName:@"territories"],
             [[Area alloc] initWithValue:@"359" andName:@"texarkana"],
             [[Area alloc] initWithValue:@"649" andName:@"texoma"],
             [[Area alloc] initWithValue:@"156" andName:@"thailand"],
             [[Area alloc] initWithValue:@"627" andName:@"the thumb"],
             [[Area alloc] initWithValue:@"387" andName:@"thunder bay"],
             [[Area alloc] initWithValue:@"181" andName:@"tijuana"],
             [[Area alloc] initWithValue:@"88" andName:@"tokyo"],
             [[Area alloc] initWithValue:@"204" andName:@"toledo"],
             [[Area alloc] initWithValue:@"280" andName:@"topeka"],
             [[Area alloc] initWithValue:@"397" andName:@"torino"],
             [[Area alloc] initWithValue:@"25" andName:@"toronto"],
             [[Area alloc] initWithValue:@"411" andName:@"toulouse"],
             [[Area alloc] initWithValue:@"332" andName:@"treasure coast"],
             [[Area alloc] initWithValue:@"323" andName:@"tri-cities, TN"],
             [[Area alloc] initWithValue:@"479" andName:@"trois-rivieres"],
             [[Area alloc] initWithValue:@"57" andName:@"tucson"],
             [[Area alloc] initWithValue:@"70" andName:@"tulsa"],
             [[Area alloc] initWithValue:@"581" andName:@"tunisia"],
             [[Area alloc] initWithValue:@"148" andName:@"turkey"],
             [[Area alloc] initWithValue:@"371" andName:@"tuscaloosa"],
             [[Area alloc] initWithValue:@"703" andName:@"tuscarawas co"],
             [[Area alloc] initWithValue:@"469" andName:@"twin falls"],
             [[Area alloc] initWithValue:@"704" andName:@"twin tiers NY/PA"],
             [[Area alloc] initWithValue:@"308" andName:@"tyler / east TX"],
             [[Area alloc] initWithValue:@"583" andName:@"ukraine"],
             [[Area alloc] initWithValue:@"215" andName:@"united arab emirates"],
             [[Area alloc] initWithValue:@"262" andName:@"upper peninsula"],
             [[Area alloc] initWithValue:@"247" andName:@"utica-rome-oneida"],
             [[Area alloc] initWithValue:@"427" andName:@"valdosta"],
             [[Area alloc] initWithValue:@"394" andName:@"valencia"],
             [[Area alloc] initWithValue:@"16" andName:@"vancouver, BC"],
             [[Area alloc] initWithValue:@"178" andName:@"venezuela"],
             [[Area alloc] initWithValue:@"310" andName:@"venice / veneto"],
             [[Area alloc] initWithValue:@"208" andName:@"ventura county"],
             [[Area alloc] initWithValue:@"507" andName:@"veracruz"],
             [[Area alloc] initWithValue:@"93" andName:@"vermont"],
             [[Area alloc] initWithValue:@"177" andName:@"victoria"],
             [[Area alloc] initWithValue:@"564" andName:@"victoria, TX"],
             [[Area alloc] initWithValue:@"122" andName:@"vienna"],
             [[Area alloc] initWithValue:@"314" andName:@"vietnam"],
             [[Area alloc] initWithValue:@"616" andName:@"virgin islands"],
             [[Area alloc] initWithValue:@"346" andName:@"visalia-tulare"],
             [[Area alloc] initWithValue:@"270" andName:@"waco"],
             [[Area alloc] initWithValue:@"10" andName:@"washington, DC"],
             [[Area alloc] initWithValue:@"567" andName:@"waterloo / cedar falls"],
             [[Area alloc] initWithValue:@"337" andName:@"watertown"],
             [[Area alloc] initWithValue:@"458" andName:@"wausau"],
             [[Area alloc] initWithValue:@"302" andName:@"wellington"],
             [[Area alloc] initWithValue:@"325" andName:@"wenatchee"],
             [[Area alloc] initWithValue:@"551" andName:@"west bank"],
             [[Area alloc] initWithValue:@"194" andName:@"west virginia (old)"],
             [[Area alloc] initWithValue:@"697" andName:@"western IL"],
             [[Area alloc] initWithValue:@"377" andName:@"western KY"],
             [[Area alloc] initWithValue:@"329" andName:@"western maryland"],
             [[Area alloc] initWithValue:@"173" andName:@"western massachusetts"],
             [[Area alloc] initWithValue:@"320" andName:@"western slope"],
             [[Area alloc] initWithValue:@"472" andName:@"whistler, BC"],
             [[Area alloc] initWithValue:@"625" andName:@"whitehorse"],
             [[Area alloc] initWithValue:@"99" andName:@"wichita"],
             [[Area alloc] initWithValue:@"365" andName:@"wichita falls"],
             [[Area alloc] initWithValue:@"463" andName:@"williamsport"],
             [[Area alloc] initWithValue:@"274" andName:@"wilmington, NC"],
             [[Area alloc] initWithValue:@"711" andName:@"winchester"],
             [[Area alloc] initWithValue:@"235" andName:@"windsor"],
             [[Area alloc] initWithValue:@"79" andName:@"winnipeg"],
             [[Area alloc] initWithValue:@"272" andName:@"winston-salem"],
             [[Area alloc] initWithValue:@"593" andName:@"wollongong"],
             [[Area alloc] initWithValue:@"240" andName:@"worcester / central MA"],
             [[Area alloc] initWithValue:@"597" andName:@"wuhan"],
             [[Area alloc] initWithValue:@"197" andName:@"wyoming"],
             [[Area alloc] initWithValue:@"603" andName:@"xi'an"],
             [[Area alloc] initWithValue:@"246" andName:@"yakima"],
             [[Area alloc] initWithValue:@"624" andName:@"yellowknife"],
             [[Area alloc] initWithValue:@"357" andName:@"york, PA"],
             [[Area alloc] initWithValue:@"252" andName:@"youngstown"],
             [[Area alloc] initWithValue:@"456" andName:@"yuba-sutter"],
             [[Area alloc] initWithValue:@"405" andName:@"yucatan"],
             [[Area alloc] initWithValue:@"370" andName:@"yuma"],
             [[Area alloc] initWithValue:@"607" andName:@"zamboanga"],
             [[Area alloc] initWithValue:@"702" andName:@"zanesville / cambridge"],
             [[Area alloc] initWithValue:@"112" andName:@"zurich"]];
}


- (Area *) findDefault {
    NSArray *areas = [self findAll];
    for (Area * area in areas) {
        if ([area.value isEqualToString:kAreaRepositoryDefault]) {
            return area;
        }
    }
    return [areas firstObject];
}

@end
